.github/workflows/build.yml
tests/test_convention.py

* One pair is not sufficient for cache test. We create a loop to test the time spent on converting

[Fix] update test_cache in test_convention

---

docs/preprocess_dataset.md
mmhuman3d/data/data_converters/agora.py
mmhuman3d/data/data_converters/coco_wholebody.py
mmhuman3d/data/data_converters/eft.py
mmhuman3d/data/data_converters/h36m.py
mmhuman3d/data/data_converters/h36m_spin.py
mmhuman3d/data/data_converters/penn_action.py
mmhuman3d/data/data_converters/surreal.py
tests/test_data_converters.py
tools/convert_datasets.py

- fix `cv2.imwrite` bug in h36m converters
- refactor to store relative instead of absolute image path
- refactor to use image prefix as folder name
- update documentation for clarify
- bug fix for agora SMPL converter

[Fix] Converters bug fix

---

CITATION.cff
README.md
README_CN.md
docs/getting_started.md
docs/preprocess_dataset.md

[Docs] Update documentations

---

configs/smplify/smplify.py
configs/smplify/smplifyx.py
configs/spin/resnet50_spin_pw3d.py
mmhuman3d/core/parametric_model/smplify.py
mmhuman3d/models/utils/smpl.py
tests/test_cameras/test_cameras.py
tests/test_models/test_architectures/test_mesh_estimator.py
tests/test_smplify.py

[Feature] Upgrade SMPLify and body models

---

mmhuman3d/core/cameras/camera_parameter.py
mmhuman3d/data/data_converters/h36m.py
mmhuman3d/data/data_structures/human_data.py
tests/test_cameras/test_camera_parameter.py

* To avoid numpy values in CameraParameter and error caused by them, we add type check to ensure their type.
* Check key in a function
* Fix some docstring in HumanData

[Fix] update camera parameter

---

mmhuman3d/core/visualization/renderer/matplotlib3d_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/base_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/segmentation_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/smpl_renderer.py
mmhuman3d/core/visualization/visualize_keypoints2d.py
mmhuman3d/core/visualization/visualize_keypoints3d.py
mmhuman3d/core/visualization/visualize_smpl.py
mmhuman3d/utils/__init__.py
mmhuman3d/utils/demo_utils.py
mmhuman3d/utils/ffmpeg_utils.py
mmhuman3d/utils/keypoint_utils.py

fix color channel and modified a function

Update merge into Vibe demo

---

mmhuman3d/data/data_structures/__init__.py
mmhuman3d/data/data_structures/smc_reader.py
tests/test_smc_reader.py

Add SMC Reader, WIP for lint fixes

[Add] Add smc reader

---

mmhuman3d/core/cameras/camera_parameters.py
mmhuman3d/data/data_converters/h36m.py
mmhuman3d/data/data_converters/pw3d.py
mmhuman3d/data/data_converters/surreal.py
tests/test_cameras/test_camera_parameter.py

* Add a method to get K, R, T in type ndarray. The dimension of K can be configured through arguement.

[Add] Get K, R, T from CameraParameter by a single method

---

docs/conf.py

Follow https://github.com/open-mmlab/mmocr/pull/655. Here is a preview demo: https://mmhuman3dyl-1993.readthedocs.io/en/latest/

[Docs] Use shared menu from openmmlab theme

---

mmhuman3d/data/data_converters/__init__.py
mmhuman3d/data/data_converters/humman.py
mmhuman3d/data/data_structures/human_data.py
mmhuman3d/data/data_structures/smc_reader.py
tests/test_data_converters.py
tests/test_smc_reader.py
tools/convert_datasets.py

[New] Add HuMMan data converter

---

mmhuman3d/core/cameras/camera_parameters.py
mmhuman3d/data/data_structures/smc_reader.py
setup.py
tests/test_cameras/test_camera_parameter.py

* load kinect parameters from SMC reader
* load iphone parameters from SMC reader
* fix url mentioned in issue https://github.com/open-mmlab/mmhuman3d/issues/85

[Feature] Link CameraParameter with SenseMocap Reader

---

mmhuman3d/data/data_converters/h36m.py

Fix the bug that h36m dataset doesn't create image folders automatically

[Fix] fix h36m data processing bug

---

tools/dist_test.sh
tools/dist_train.sh

[Add] create script for multi-gpu testing and training without slurm

---

mmhuman3d/data/data_converters/humman.py
mmhuman3d/data/data_structures/smc_reader.py
mmhuman3d/data/datasets/pipelines/loading.py
mmhuman3d/models/body_models/__init__.py
mmhuman3d/models/body_models/utils.py
tests/test_body_model.py
tests/test_models/test_body_models/test_smpl.py
tests/test_models/test_body_models/test_utils.py

[Feature] Upgrade SMCReader to support rigid transformation of SMPL

---

configs/vibe/README.md
configs/vibe/resnet50_vibe_pw3d.py

Resolves #99
update the url of `spin.pth`.

[Update] Update the url of `spin.pth`

---

mmhuman3d/core/conventions/keypoints_mapping/human_data.py
requirements/runtime.txt

Resolve #116 
Remove duplicate limbs in human_data.

[Fix] Remove duplicate limbs

---

docs/install.md

* Install ffmpeg after conda virtual env created.

[Fix] Fix installation docs for ffmpeg

---

demo/estimate_smpl_image.py
demo/estimate_smpl_video.py
mmhuman3d/core/cameras/cameras.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/base_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/lights.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/mesh_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/meshes.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/pointcloud_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/segmentation_renderer.py
mmhuman3d/core/visualization/renderer/torch3d_renderer/utils.py
mmhuman3d/core/visualization/visualize_keypoints2d.py
mmhuman3d/core/visualization/visualize_smpl.py
mmhuman3d/utils/ffmpeg_utils.py
mmhuman3d/utils/mesh_utils.py
tests/test_utils/test_mesh_utils.py

Fix the unresolved questions in PR107.

[Fix] Resolve questions in uv_map

---

mmhuman3d/core/visualization/visualize_smpl.py

remove unused image_array in line 75

[Fix] fix typo in visualize_smpl.py

---

mmhuman3d/core/cameras/cameras.py

Related to issue https://github.com/open-mmlab/mmhuman3d/issues/167
* fix wrong in_ndc kwargs and remove useless is_perspective

[Fix] Fix wrong in_ndc kwargs and remove useless is_perspective

---

configs/pare/hrnet_w32_conv_pare_coco.py
configs/pare/hrnet_w32_conv_pare_coco_cache.py
configs/pare/hrnet_w32_conv_pare_mix.py
configs/pare/hrnet_w32_conv_pare_mix_cache.py
configs/pare/hrnet_w32_conv_pare_mix_no_mosh.py

1. add `img_res = 224` to fix pare model infer error
2. format pare config reference [spin/resnet50_spin_pw3d.py](https://github.com/open-mmlab/mmhuman3d/blob/main/configs/spin/resnet50_spin_pw3d.py)
#172

[Fix] Fix & Format pare config

---

configs/spin/README.md
configs/spin/resnet50_spin_pw3d.py
configs/spin/resnet50_spin_pw3d_cache.py
mmhuman3d/data/datasets/human_image_dataset.py
mmhuman3d/models/architectures/mesh_estimator.py
mmhuman3d/models/registrants/smplify.py
tests/test_models/test_architectures/test_mesh_estimator.py

Modification Log:
1. Fix bugs of camera parameters in registration
2. Fix bugs of `sample_idx` in `fits_dict`
3. Add cache to SPIN training
4. Refactor registration configuration in `mesh_estimator` to support using `static_fit` only
5. Refactor model optimization
6. Add `quiet` parameter to `simplify`
**Accuracy Comparison**
|  | MPJPE | PA-MPJPE |
|:------:|:-------:|:------:|
| Old | 96.06 | 59.06 |
| New | **94.11** | **57.54** |

[Refactor] Refactor Registration and Improve Performance of SPIN

---

docs/install.md
docs_zh-CN/install.md

Update install.md to fix two problems.

[Doc] Update install.md to address dependency conflicts

---

README.md
configs/gta_human/README.md
docs/install.md
docs_zh-CN/install.md

This PR updates the following:

[Doc] Update GTA-Human, Main Readme, and Install Guide

---

configs/_base_/post_processing/gaus1d.py
configs/_base_/post_processing/guas1d.py
docs/getting_started.md
docs_zh-CN/getting_started.md

[Fix] Fix bugs in guas1d config

---

mmhuman3d/core/renderer/mpr_renderer/cuda/rasterizer_kernel.cu

[Fix] Fix bug for the real-time renderer

---

configs/pymafx/README.md
docs/model_zoo.md
docs_zh-CN/model_zoo.md

Add `ExPose` and `PyMAF-X` links to Baseline.

Add PyMAF-X doc

---

configs/pymafx/README.md
demo/mmpose_cfg/hrnet_w48_coco_wholebody_384x288_dark_plus.py
demo/pymafx_estimate_smplx.py
tests/test_pymafx_pipeline.py

[Feature] Add mmpose in PyMAF-X

---

configs/balanced_mse/resnet50_spin_ihmr_ft_baseline.py
configs/balanced_mse/resnet50_spin_ihmr_ft_bmc.py
configs/gta_human/hmr/resnet50_hmr_gta_bt.py
configs/gta_human/hmr/resnet50_hmr_gta_ft.py
configs/gta_human/pare/hrnet_w32_conv_pare_gta_ft.py
configs/gta_human/spin/resnet50_spin_gta_ft.py
configs/hmr/resnet50_hmr_pw3d.py
configs/hmr/resnet50_hmr_pw3d_e50_cache.py
configs/hybrik/resnet34_hybrik_mixed.py
configs/pare/hrnet_w32_conv_pare_coco.py
configs/pare/hrnet_w32_conv_pare_coco_cache.py
configs/pare/hrnet_w32_conv_pare_mix.py
configs/pare/hrnet_w32_conv_pare_mix_cache.py
configs/pare/hrnet_w32_conv_pare_mix_no_mosh.py
configs/spin/resnet50_spin_pw3d.py
configs/spin/resnet50_spin_pw3d_cache.py
configs/vibe/resnet50_vibe_pw3d.py

Previously, "img_res" variable is defined in most of the configs, but not used

[Fix] Modify configs use "img_res"

---

configs/gta_human/README.md
configs/hmr/star_pw3d.py
demo/estimate_star.py
docs/human_data.md
docs_zh-CN/human_data.md
mmhuman3d/core/conventions/segmentation/__init__.py
mmhuman3d/core/renderer/torch3d_renderer/meshes.py
mmhuman3d/core/visualization/visualize_smpl.py
mmhuman3d/models/body_models/star.py
requirements/runtime.txt

* fix star lbs
* add demo/render_star to visualize star

Update STAR lbs & render
